services:
  app:
    build:
      context: .
      dockerfile: src/FindAirConditioners.Web/Dockerfile
    container_name: findac-app
    restart: unless-stopped
    env_file:
      - .env.aws
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "8080:8080"
